### PR TITLE
refactor handling of DLC input validation

### PR DESCRIPTION
**Pull request by conduition**
- Removed trailing whitespace (my editor does this automatically so i separated it in the first commit)
- Refactor handling of inputs for DLC registration: 
  - Raise `TransactionErrors` instead of returning false, to give callers better feedback and to mirror the behavior of other input validation code
  - Avoid duplicating SCT validation logic in `mint/dlc.py`. Instead rely on the recursive SCT secret verification logic in `mint/conditions.py`.
- Rename `DLCWitness` to `SCTWitness`, reflecting the fact that this data structure is the witness to an SCT secret (including those which may not be related to DLCs at all)

### CODE REVIEW

**Review by a1denvalu3 — APPROVED** [review]
lgtm

**Comment by conduition** [comment]
Tests are failing, i need some additional time to get unit test runners working on my machine

**Comment by conduition** [comment]
I found the cause of my woes: https://github.com/cashubtc/nutshell/pull/607

**Comment by conduition** [comment]
I've updated this PR to target the latest commit 6b1d04cdfa62aecc90aa8d413ffb4a2938dd98c3 in https://github.com/cashubtc/nutshell/pull/576. The overall changes are the same:

- Whitespace formatting fixes https://github.com/lollerfirst/nutshell/pull/1/commits/c58cf9b9ba757119d53d5386b42f3d4d7f4d3894
- Rename `DLCWitness` to `SCTWitness` https://github.com/lollerfirst/nutshell/pull/1/commits/97684a6d4d614b6284e86965ed2300bcb094e1e6
- Raise errors instead of returning false. https://github.com/lollerfirst/nutshell/pull/1/commits/42964e79b143f7007e19ec4f8505d6bc44dc6800
- Refactor how DLC input validation is handled https://github.com/lollerfirst/nutshell/pull/1/commits/0b5c1912f7ef2d11a6b83121f3448e7390b63d65
- [new] Fix a bunch of linter errors https://github.com/lollerfirst/nutshell/pull/1/commits/1f287d3ce4a9e19945f513ba045a025f19e9f9dd (validated with `make check`)

I've confirmed tests pass on my machine with `make test`, though only if I apply https://github.com/cashubtc/nutshell/pull/607 on top of this PR.

**Comment by a1denvalu3** [comment]
Good job. I'm gonna merge this. Unfortunately some tests fail because I fucked up. I changed the migration for the DLC table to have the column settled of type BIT instead of BOOL, as I had read that BOOL is not supported across different DBs while BIT is. Apparently it doesn't like the 0 default value for it.

**Pull request merged**
